In [1]:
import pandas as pd
import numpy as np
import pandas_datareader.data as web
from datetime import datetime

In [10]:
# adjust the variables below
ticker = 'AAPL'
start = datetime(1990,1,1)
end = datetime(2020,1,1)

df = web.DataReader(ticker, 'stooq', start, end)
df

                Open      High       Low     Close     Volume
Date
2019-12-31  71.42100  72.34200  71.31900  72.33500  102490623
2019-12-30  71.30500  72.10300  70.26000  71.81200  146380989
2019-12-27  71.71500  72.41500  70.97400  71.38800  148545967
2019-12-26  70.16400  71.43400  70.13500  71.41600   94722440
2019-12-24  70.13200  70.18100  69.69300  70.02700   49198965
...              ...       ...       ...       ...        ...
1990-01-08   0.28723   0.29092   0.28319   0.29092  118470824
1990-01-05   0.28905   0.29268   0.28319   0.28905  143826725
1990-01-04   0.29268   0.29665   0.28504   0.28781  258365560
1990-01-03   0.29092   0.29092   0.28723   0.28723  242598119
1990-01-02   0.26979   0.28723   0.26793   0.28504  213676036

[7558 rows x 5 columns]